### PR TITLE
Update bubble.yaml

### PR DESCRIPTION
**Pull request by UberDudePL**
Hello,

I am not sure if you are interested in this but I've made the theme to switch between light and dark when set to auto as per phone or PC set up.

Have a good day

### CODE REVIEW

**Comment by Clooos** [comment]
Thank you! I'm a bit busy these days but I can't wait to try it!

**Comment by UberDudePL** [comment]
One thing that I noticed, has not used it before so far 😂 as I am mostly using Studio Code Server to edit dashboard in YAML. The code editor background color that I have used makes it very hard to read. I suggest to change to #eff1f5 - the overall background. Combination of dark grey and light pink is not good 🤪

If you want I can share with you some screenshots of my dashboard to show the colors etc.

**Comment by Clooos** [comment]
I totally agree, this can be a good improvement.

And I would love to see some screenshots as well 😁

**Comment by UberDudePL** [comment]
From PC
image
Phone
image
Tablet
image

I can see on the last one some sub-buttons are cut. Haven't worked much with Tablet yet. Just added layout for it for future, when I put one on the wall :)

My dashboard is based on yourMobile First Dashboard (I've loved it, still am but Bubbles brings it to next level!) but I've implemented views and layouts to be adaptive based on resolution. I can share some code as well

**Comment by Clooos** [comment]
I love it! Thank you so much again!

**Comment by UberDudePL** [comment]
No, no, it is me who is thankful, I am glad that I could give a little back :)

**Pull request merged**
